server:
  port: 8801
spring:
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        output:
          destination: studyexchange
          content-type: application/json
          binder: defaultRabbit
  application:
    name: cloud-stream-provider

eureka:
  instance:
    instance-id: send8801.com
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 #如果现在超过5秒的间隔（默认是90秒）
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka