server:
  port: 3344
spring:
  cloud:
    config:
      server:
        git:
          search-paths:
            - springcloud-config
          uri: git@github.com:90july/springcloud-config.git
      label: master
  application:
    name: cloud-config-server
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'
logging:
  level:
    org.springframework.amqp: debug

