server:
  port: 3344
spring:
  cloud:
    config:
      server:
        git:
          search-paths:
            - springcloud-config
          uri: git@github.com:90july/springcloud-config.git
      label: master
  application:
    name: cloud-config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka