server:
  port: 9527
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: cloud-gateway-service
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment-routh #路由的id，没有固定规则但要求
          uri: lb://cloud-payment-service	 #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由

        - id: payment-routh #路由的id，没有固定规则但要求
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/** #断言，路径相匹配的进行路由
#            - After=2020-03-14T20:06:32.597+08:00[GMT+08:00]
#            - Cookie=username,zzyy
#            - Header=X-Request-Id,\d+
#            - Method=GET
#            - Query=username, \d+
#            - Host=**.atguigu.com

      discovery:
        locator:
          enabled: true #开启动态路有功能
logging:
  level:
    org.springframework.cloud: debug